Add affiliation when enrich
LF-Engineering/da-ds pull request #11
Opened 2021-01-08 12:07 UTC by enkhalifapro

2021-01-08 12:23 UTC, lukaszgryglicki requested changes
All other da-ds data sources already have affiliations support in [affs.go](https://github.com/LF-Engineering/da-ds/blob/master/affs.go) file and support for mass/bulk uploading new identities to SH DB in [ds.go](https://github.com/LF-Engineering/da-ds/blob/master/ds.go#L178) file. Your code will duplicate this, and it misses 5-step algorithm: https://github.com/LF-Engineering/da-ds/blob/master/affs.go#L246 (we should either use this code which supports everything that grimoire did - by talking to SH DB directly - to be fastest and using bulk inserts for identities, or we should use dev-affiliation-api) - we don't want a new affiliations handler that confuses me and duplicates functionalities we already have. cc @fayazg @1010sachin

2021-01-19 11:38 UTC, code-sleuth approved these changes
/lgtm

2021-01-19 11:50 UTC, ajinkyan83 commented on cmd/dads/dads.go
> +
If possible, can remove empty lines like this.

2021-01-19 11:50 UTC, ajinkyan83 approved these changes
/lgtm

2021-01-25 13:52 UTC, lukaszgryglicki approved these changes
/lgtm

2021-01-25 13:54 UTC, merged