[googleGroups]: update env variables and credentials files
LF-Engineering/da-ds pull request #35
Opened 2021-03-30 14:13 UTC by code-sleuth

2021-03-30 14:35 UTC, lukaszgryglicki commented on googlegroups/const.go
> +	TokenFile = "/Users/code/lf/da/da-ds/googlegroups/token.json"
If we merge this, how can you be sure that SDS image will have those files?

2021-03-30 14:35 UTC, lukaszgryglicki commented on cmd/dads/dads.go
> +	authClientID := os.Getenv("AUTH0_CLIENT_ID")
This will change the name (remove root `DA_GOOGLEGROUP_`) from env variables - it will need SDS side support to pass this for da-ds - unless it runs from outside of SDS.

2021-03-31 13:10 UTC, code-sleuth commented on googlegroups/const.go
> +	TokenFile = "/Users/code/lf/da/da-ds/googlegroups/token.json"
I have the actual files stored on the test ec2 box. `/root/.ggcred/*`

2021-03-31 14:15 UTC, lukaszgryglicki commented on googlegroups/const.go
> +	TokenFile = "/Users/code/lf/da/da-ds/googlegroups/token.json"
Yeah, we can do this, but I will need them locally and add copying of those files while building the SDS image.
I took the other rounte with base64 encoding JSON and then putting it in `*.secret` file, like the `AUTH0_DATA` approach - but we can also go your way, but you will have to update SDS build image script, somewhere around [here](https://github.com/LF-Engineering/sync-data-sources/blob/master/docker-images/build.sh#L48) and [there](https://github.com/LF-Engineering/sync-data-sources/blob/master/docker-images/build.sh#L51), and then in [Dockerfile](https://github.com/LF-Engineering/sync-data-sources/blob/master/docker-images/Dockerfile#L35-L37).

2021-04-01 05:32 UTC, lukaszgryglicki commented
Please ping me when the final version is ready for review.

2021-04-01 09:36 UTC, code-sleuth commented
@lukaszgryglicki the final version is ready for review

2021-04-01 11:13 UTC, lukaszgryglicki requested changes
/lgtm

2021-04-01 11:20 UTC, lukaszgryglicki approved these changes

2021-04-01 11:24 UTC, merged