DA-3981: only add docs to es when add identity is ok
LF-Engineering/da-ds pull request #53
Opened 2021-05-26 18:49 UTC by aultron

2021-05-26 18:57 UTC, lukaszgryglicki requested changes
I don't see how this ensures that identity was added.

2021-05-26 18:57 UTC, lukaszgryglicki commented on googlegroups/enricher.go
> +		e.ensureAddIdentity(userIdentity)
I don't see any "ensurement" here, you just wait 5 minutes and then you don't check if that succeeded or not.

2021-05-26 19:00 UTC, aultron commented on googlegroups/enricher.go
> +		e.ensureAddIdentity(userIdentity)
we dont want to write to es if a call to the affiliations api fails, could be because of some downtime or expired token. we cant predict the reson at this point so we wait till its available.

2021-05-26 19:02 UTC, lukaszgryglicki commented on googlegroups/enricher.go
> +		e.ensureAddIdentity(userIdentity)
hmmm, I think we need additional pair of eyes to approve this. I dont like this solution, I would either fail or use the gap handler.

2021-05-26 19:04 UTC, aultron commented on googlegroups/enricher.go
> +		e.ensureAddIdentity(userIdentity)
cc @fayazg @khalifapro

2021-05-26 19:07 UTC, lukaszgryglicki commented on googlegroups/enricher.go
> +		e.ensureAddIdentity(userIdentity)
Maybe it's just OK, I just want to be sure.

2021-05-26 19:08 UTC, aultron commented on googlegroups/enricher.go
> +		e.ensureAddIdentity(userIdentity)
yup, lets get everyones input since we'll be applying this to every datasource.

2021-06-07 14:04 UTC, aultron commented
closing this as i implemented the same functionality at the libraries level [here](https://github.com/LF-Engineering/dev-analytics-libraries/pull/64/files)

2021-06-07 14:04 UTC, closed without merging