dsGit: hanlde parent commits
LF-Engineering/da-ds pull request #76
Opened 2021-07-30 14:49 UTC by aultron

2021-07-30 15:10 UTC, lukaszgryglicki commented on dsgit.go
> +			e = EnrichPairProgrammingItem(commits, rich.(map[string]interface{}))
Have you teste dthis in non-PP mode, is this needed in non-PP mode? Because this code runs always, not only in PP.

2021-07-30 15:13 UTC, lukaszgryglicki commented on dsgit.go
> +	commits []string
Shouldn't it start from an uppercase? Shouldn't it have a comment?
Is this really golbal for the entire run of da-ds git? Meant to store all commits from that run?
What if that runs in incremental mode (like next sync after a full sync)? It won't have all commits hases for a given repo then, does it matter?
Please answer my feedback confirming that it is exactly what you wanted so that you took into consideration non-PP mode and non-full sync.

2021-07-30 15:13 UTC, lukaszgryglicki reviewed
Please see my comments and confirm that you took them into account - then I can approve.

2021-07-30 15:14 UTC, lukaszgryglicki commented
And with that PR is the #75 still needed?

2021-07-30 16:26 UTC, aultron commented on dsgit.go
> +			e = EnrichPairProgrammingItem(commits, rich.(map[string]interface{}))
its ok to run for non pair programming commits, its handling parent commits from duplicates. I'll change the function name.

2021-07-30 16:26 UTC, aultron commented on dsgit.go
> +	commits []string
Its global, but i'm now thinking of cases where  sds is stopped and rerun. This isn't persistent. I'll add an es index to keep track of a repo and all its hashes.

2021-07-30 16:34 UTC, lukaszgryglicki commented on dsgit.go
> +			e = EnrichPairProgrammingItem(commits, rich.(map[string]interface{}))
not really sure what `parent commit` mean... but if you're sure it won't break anything in non-PP mode then it's OK.

2021-07-30 16:35 UTC, lukaszgryglicki commented on dsgit.go
> +	commits []string
Not even stopped. This that repo was *correctly* synced once, and then the next incremental sync happen - will this handle OK?

2021-07-31 01:20 UTC, aultron commented on dsgit.go
> +	commits []string
the new change i've added where we have a map (dictionary of repo keys and a list of commit hashes) handles this well even for incremental syncs.

2021-07-31 01:22 UTC, aultron commented on dsgit.go
> +			e = EnrichPairProgrammingItem(commits, rich.(map[string]interface{}))
parent commit is the first document with a hash that multiple docs have. Pair programming documents have the same hash so the first document to be enriched will be tagged as parent commit.

It will also help us get away from cardinality aggregations and instead use sum of is_parent_commit.

2021-08-02 05:58 UTC, lukaszgryglicki commented on dsgit.go
> +				return
In case of error mtx won't be unlocked and deadlock can happen.

2021-08-02 06:01 UTC, lukaszgryglicki commented on dsgit.go
> +		if ok := Find(repoCommits, commitString); ok {
Why not store commits hashes as maps, not arrays - you won't need to iterate over a slice to find if the commit is there or not?
Like instead of having `map[string][]string` use `map[string]map[string]struct{}`?

2021-08-02 06:01 UTC, lukaszgryglicki requested changes
Had few more comments.

2021-08-02 09:11 UTC, aultron commented on dsgit.go
> +			CommitsHash[repoString] = map[string]struct{}{commitString: emptyStruct}
the inner map isn't initialized so this will cause a panic. working on a fix

2021-08-02 09:17 UTC, lukaszgryglicki commented on dsgit.go
> +			CommitsHash[repoString] = map[string]struct{}{commitString: emptyStruct}
Yeah, so you code when the inner map is nil and my code if it isn't.

2021-08-02 09:58 UTC, lukaszgryglicki commented on dsgit.go
> +	// CommitsHash is a slice of commit hashes for each repo
`/s/slice/map/`

2021-08-02 10:00 UTC, lukaszgryglicki commented on dsgit.go
> +	}
shouldn't we have `else` (when `repo_name` is not in the map, and in that `else` create a map for commits like
```
} else {
  CommitsHash[repoString] = make(map[string]struct{})
}
```
?

2021-08-02 10:01 UTC, lukaszgryglicki commented on dsgit.go
> +	}
Ohh you actually do this when commit hash is found, nevermind then.

2021-08-02 10:02 UTC, lukaszgryglicki approved these changes
/lgtm

2021-08-02 10:13 UTC, aultron commented on dsgit.go
> +				return
fixed

2021-08-02 11:04 UTC, merged

2021-08-02 11:06 UTC, lukaszgryglicki commented
OK, I'll build a new SDS on this, but please note that if you want *all* data to contain your new flags - you must drop all `test` git rich indices (you can leave raws intact).

2021-08-02 11:47 UTC, lukaszgryglicki commented
SDS images rebuilt.